### ISSUE TITLE
Setup a home server for matrix

### ISSUE THREAD

**Issue by anandology** [fossunited/infra#3]
[Matrix] is an open-source project for decentralised, real-time communication. [Synapse][] is the reference implementation of the server.

It would be nice toe try Matrix for FOSS United. 

## Tasks
- [ ]  Setup a Matrix server for FOSS United
- [ ] Setup a bridge with the existing telegram group

[Matrix]: https://matrix.org
[Synapse]: https://github.com/matrix-org/synapse

## Resources

Installation Instructions
<https://github.com/matrix-org/synapse/blob/develop/INSTALL.md>

Matrix (An open network for secure, decentralized communication) server setup using Ansible and Docker
<https://github.com/spantaleev/matrix-docker-ansible-deploy>

---
#1

**Comment by anandology** [comment]
Tasks for setting up matrix server. 

- [x] Start a digitalocean droplet 
- [x] Setup DNS record for matrix.fossunited.org
- [ ] Setup [wellknown delegation](https://github.com/matrix-org/synapse/blob/develop/docs/delegate.md) on fossunited.org
- [ ] Install all the required software using ansible

**Comment by anandology** [comment]
I've setup one using  https://github.com/spantaleev/matrix-docker-ansible-deploy, but I'm not quite happy. The setup is too complex to manage.

I'm going to trying installing Synapse directly. 

Sillius Soddus on Telegram suggested to try [Dendrite][2], a matrix server written in Go.

The [Federation Tester][1] can be used to verify your deployment.

[1]: https://federationtester.matrix.org/
[2]: https://github.com/matrix-org/dendrite
