### ISSUE TITLE
Host listmonk for fossunited

### ISSUE THREAD

**Issue by anandology** [fossunited/infra#6]
Setup a listmonk instance for fossunited.

## Tasks
- [x] setup a node on linode for hosting this
- [x] setup DNS for listmonk.fossunited.org
- [x] Install listmonk
- [x] setup nginx site for listmonk.fossunited.org
- [x] setup letsencrypt ssl certificate
- [x] setup smtp credentials in the config
- [x] setup an email template

**Comment by anandology** [comment]
@nikochiko you can go ahead and setup listmonk for fossunited.

**Comment by nikochiko** [comment]
The mentioned tasks are done. SMTP setup, etc is remaining.

https://listmonk.fossunited.org

* There's a `listmonk` system user that owns `/opt/listmonk`, the binary and config files are stored there. config file can only be read by `listmonk` user and root.
* Postgres is hosted locally, and accepts only local connections
* Nginx proxies listmonk.fossunited.org to listmonk's local address, SSL is setup with certbot and lets encrypt.
* a systemd service is used to keep listmonk alive after crashes and restarts

**Comment by nikochiko** [comment]
SMTP is setup and working,

PS. have edited description to fill that checkmark, and added item one more to setup email template

**Comment by nikochiko** [comment]
Template is setup and working.
Vishal sent the FOSS Meetup mail yesterday using the template. Here is a screenshot of that from gmail:
![image](https://user-images.githubusercontent.com/37668193/148494910-2225ce13-7a80-4215-8ad7-c39a3239d46c.png)

(The padding is set correctly, but the image overflowed in this email. I think adding a `style="max-width: 100%;"` for images should avoid this in the future.)
